package kfx

// Subset of Calibre YJ_PROPERTY_INFO (yj_to_epub_properties.py L84+) for Ion keys that map to a
// single CSS property name without an enum table. Enum-backed properties remain handled in kfx.go
// until migrated to structured entries.
var yjPropertySimpleCSS = map[string]string{
	"$479": "background-image",
	"$480": "-kfx-background-positionx",
	"$481": "-kfx-background-positiony",
	"$482": "-kfx-background-sizex",
	"$483": "-kfx-background-sizey",
	"$31":  "-kfx-baseline-shift",
	"$83":  "border-color",
	"$86":  "border-bottom-color",
	"$85":  "border-left-color",
	"$87":  "border-right-color",
	"$84":  "border-top-color",
	"$461": "border-bottom-left-radius",
	"$462": "border-bottom-right-radius",
	"$459": "border-top-left-radius",
	"$460": "border-top-right-radius",
	"$457": "-webkit-border-horizontal-spacing",
	"$456": "-webkit-border-vertical-spacing",
	"$93":  "border-width",
	"$96":  "border-bottom-width",
	"$95":  "border-left-width",
	"$97":  "border-right-width",
	"$94":  "border-top-width",
	"$60":  "bottom",
	"$116": "column-rule-color",
	"$70":  "-kfx-fill-color",
	"$72":  "-kfx-fill-opacity",
	"$11":  "font-family",
	"$16":  "font-size",
	"$57":  "height",
	"$785": "-kfx-keep-lines-together",
	"$10":  "-kfx-attrib-xml-lang",
	"$761": "-kfx-layout-hints",
	"$59":  "left",
	"$32":  "letter-spacing",
	"$577": "-kfx-link-color",
	"$576": "-kfx-visited-color",
	"$503": "list-style-image",
	"$46":  "margin",
	"$49":  "margin-bottom",
	"$48":  "margin-left",
	"$50":  "margin-right",
	"$47":  "margin-top",
	"$64":  "max-height",
	"$65":  "max-width",
	"$62":  "min-height",
	"$63":  "min-width",
	"$105": "outline-color",
	"$106": "outline-offset",
	"$108": "outline-width",
	"$555": "text-decoration-color",
	"$51":  "padding",
	"$54":  "padding-bottom",
	"$53":  "padding-left",
	"$55":  "padding-right",
	"$52":  "padding-top",
	"$61":  "right",
	"$496": "box-shadow",
	"$75":  "-webkit-text-stroke-color",
	"$531": "-svg-stroke-dasharray",
	"$532": "-svg-stroke-dashoffset",
	"$530": "-svg-stroke-miterlimit",
	"$76":  "-webkit-text-stroke-width",
	"$173": "-kfx-style-name",
	"$148": "-kfx-attrib-colspan",
	"$149": "-kfx-attrib-rowspan",
	"$21":  "background-color",
	"$528": "background-image",
	"$19":  "color",
	"$718": "text-emphasis-color",
	"$36":  "text-indent",
	"$497": "text-shadow",
	"$58":  "top",
	"$98":  "transform",
	"$549": "transform-origin",
	"$56":  "width",
	"$33":  "word-spacing",
	"$650": "-amzn-shape-outside",
	"$646": "-kfx-collision",
}

// YJPropertySimpleCSSName returns the CSS property name for a simple (non-enum) YJ Ion key.
func YJPropertySimpleCSSName(yjKey string) (string, bool) {
	v, ok := yjPropertySimpleCSS[yjKey]
	return v, ok
}
