package kfx

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// Golden-file test: YJ symbol catalog parity with Calibre Python reference.
//
// This test loads internal/kfx/testdata/yj_symbols_golden.json (generated by
// scripts/export_yj_symbol_catalog.py from the Calibre Python source) and
// verifies that Go's sharedTable() produces matching name, version, and
// per-SID symbol text.
//
// Regenerate golden:
//   python3 scripts/export_yj_symbol_catalog.py > internal/kfx/testdata/yj_symbols_golden.json
// ---------------------------------------------------------------------------

// yjSymbolsGolden maps the JSON structure produced by the export script.
type yjSymbolsGolden struct {
	Name               string   `json:"name"`
	Version            int      `json:"version"`
	SymbolCount        int      `json:"symbol_count"`
	SymbolsRaw         []string `json:"symbols_raw"`
	SymbolsNormalized  []string `json:"symbols_normalized"`
}

func loadYjSymbolsGolden(t *testing.T) yjSymbolsGolden {
	t.Helper()
	raw, err := os.ReadFile("testdata/yj_symbols_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var g yjSymbolsGolden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	return g
}

func TestYJSymbolCatalog_NameAndVersion(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()

	if tbl.Name() != g.Name {
		t.Errorf("sharedTable name = %q, want %q", tbl.Name(), g.Name)
	}
	if tbl.Version() != g.Version {
		t.Errorf("sharedTable version = %d, want %d", tbl.Version(), g.Version)
	}
}

func TestYJSymbolCatalog_PythonSymbolsMatch(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()

	// Verify every Python normalized symbol matches Go at the corresponding SID.
	// Python symbols start at SID 10, so golden index i = SID 10+i.
	var mismatches []string
	for i, want := range g.SymbolsNormalized {
		sid := 10 + i
		if i >= len(goSyms) {
			mismatches = append(mismatches, fmt.Sprintf("SID %d: Go table too short (len=%d, need ≥%d)", sid, len(goSyms), i+1))
			continue
		}
		got := goSyms[i]
		if got != want {
			mismatches = append(mismatches, fmt.Sprintf("SID %d: Go=%q Python=%q", sid, got, want))
		}
	}

	if len(mismatches) > 0 {
		// Show first 20 mismatches to keep output readable
		limit := len(mismatches)
		if limit > 20 {
			limit = 20
		}
		t.Errorf("Go vs Python symbol mismatches (%d total, showing first %d):\n  %s",
			len(mismatches), limit, strings.Join(mismatches[:limit], "\n  "))
	}
}

func TestYJSymbolCatalog_LengthParity(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()
	pyLen := g.SymbolCount
	goLen := len(goSyms)

	if goLen == pyLen {
		return // exact match
	}

	// Go currently extends beyond Python's 842 symbols with placeholder entries
	// up to $1000 (991 total). This is intentional: the extra SIDs are simple
	// "$N" placeholders not yet present in the Calibre reference.
	//
	// If Go is LONGER, we just log it (not a failure). The Python range SIDs
	// are checked in TestYJSymbolCatalog_PythonSymbolsMatch above.
	//
	// If Go is SHORTER, that's a real problem — we'd be missing symbols that
	// Calibre defines.
	if goLen < pyLen {
		t.Errorf("Go table has %d symbols, but Python defines %d — Go is missing %d symbols (SIDs %d–%d)",
			goLen, pyLen, pyLen-goLen, 10+goLen, 10+pyLen-1)
		return
	}

	// Go is longer than Python — verify the extra symbols are simple $N placeholders
	t.Logf("NOTE: Go table has %d symbols, Python has %d. Extra %d Go symbols (SIDs %d–%d) are placeholders.",
		goLen, pyLen, goLen-pyLen, 10+pyLen, 10+goLen-1)

	for i := pyLen; i < goLen; i++ {
		sid := 10 + i
		expected := fmt.Sprintf("$%d", sid)
		if goSyms[i] != expected {
			t.Errorf("Extra Go symbol at index %d (SID %d) = %q, expected placeholder %q",
				i, sid, goSyms[i], expected)
		}
	}
}

func TestYJSymbolCatalog_NoUnexpectedSymbols(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()

	// Build a set of all unique symbols Go produces
	seen := make(map[string]int)
	for i, s := range goSyms {
		if s == "" {
			t.Errorf("Go symbol at index %d (SID %d) is empty", i, 10+i)
			continue
		}
		if _, dup := seen[s]; dup {
			t.Errorf("Duplicate Go symbol %q at indices %d and %d", s, seen[s], i)
		}
		seen[s] = i
	}

	// All Python raw symbols that have "?" should map to a normalized form
	// that matches Go's symbol text
	qSymbols := make(map[string]bool)
	for _, raw := range g.SymbolsRaw {
		if strings.HasSuffix(raw, "?") {
			normalized := strings.TrimSuffix(raw, "?")
			qSymbols[normalized] = true
		}
	}

	// Report how many Python symbols had the "?" flag
	t.Logf("Python symbols with ? suffix: %d/%d", len(qSymbols), g.SymbolCount)
}

func TestYJSymbolCatalog_GoldenHash(t *testing.T) {
	// This test serializes the golden's symbols_normalized and computes a hash,
	// providing a quick fingerprint that catches any Python-side change.
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()

	// Build the Go equivalent of symbols_normalized up to Python's length
	goNorm := make([]string, g.SymbolCount)
	for i := 0; i < g.SymbolCount && i < len(goSyms); i++ {
		goNorm[i] = goSyms[i]
	}

	// Serialize both for comparison
	pyJSON, _ := json.Marshal(g.SymbolsNormalized)
	goJSON, _ := json.Marshal(goNorm)

	if string(pyJSON) != string(goJSON) {
		// Find first difference
		pyLines := strings.Split(string(pyJSON), ",")
		goLines := strings.Split(string(goJSON), ",")
		minLen := len(pyLines)
		if len(goLines) < minLen {
			minLen = len(goLines)
		}
		var diffs []string
		for i := 0; i < minLen; i++ {
			if pyLines[i] != goLines[i] {
				diffs = append(diffs, fmt.Sprintf("  index %d: Python=%s  Go=%s", i, pyLines[i], goLines[i]))
				if len(diffs) >= 10 {
					diffs = append(diffs, "  ... (more diffs)")
					break
				}
			}
		}
		if len(pyLines) != len(goLines) {
			diffs = append(diffs, fmt.Sprintf("  length: Python=%d  Go=%d", len(pyLines), len(goLines)))
		}
		sort.Strings(diffs)
		t.Errorf("Go symbols don't match golden. First diffs:\n%s", strings.Join(diffs, "\n"))
	}
}
