package kfx

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// Golden-file test: YJ semantic symbol catalog parity with catalog.ion.
//
// This test loads internal/kfx/testdata/yj_symbols_golden.json (generated by
// scripts/export_yj_symbol_catalog.py from catalog.ion) and verifies that
// Go's sharedTable() produces matching name, version, and per-SID symbol text.
//
// Regenerate golden:
//   python3 scripts/export_yj_symbol_catalog.py > internal/kfx/testdata/yj_symbols_golden.json
// ---------------------------------------------------------------------------

// yjSymbolsGolden maps the JSON structure produced by the export script.
type yjSymbolsGolden struct {
	Name        string   `json:"name"`
	Version     int      `json:"version"`
	SymbolCount int      `json:"symbol_count"`
	Symbols     []string `json:"symbols"`
}

func loadYjSymbolsGolden(t *testing.T) yjSymbolsGolden {
	t.Helper()
	raw, err := os.ReadFile("testdata/yj_symbols_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var g yjSymbolsGolden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	return g
}

func TestYJSymbolCatalog_NameAndVersion(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()

	if tbl.Name() != g.Name {
		t.Errorf("sharedTable name = %q, want %q", tbl.Name(), g.Name)
	}
	if tbl.Version() != g.Version {
		t.Errorf("sharedTable version = %d, want %d", tbl.Version(), g.Version)
	}
}

func TestYJSymbolCatalog_SymbolsMatchGolden(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()

	// Verify every golden symbol matches Go at the corresponding index.
	// Golden index i = SID 10+i.
	var mismatches []string
	for i, want := range g.Symbols {
		sid := 10 + i
		if i >= len(goSyms) {
			mismatches = append(mismatches, fmt.Sprintf("SID %d: Go table too short (len=%d, need ≥%d)", sid, len(goSyms), i+1))
			continue
		}
		got := goSyms[i]
		if got != want {
			mismatches = append(mismatches, fmt.Sprintf("SID %d: Go=%q Golden=%q", sid, got, want))
		}
	}

	if len(mismatches) > 0 {
		limit := len(mismatches)
		if limit > 20 {
			limit = 20
		}
		t.Errorf("Go vs golden symbol mismatches (%d total, showing first %d):\n  %s",
			len(mismatches), limit, strings.Join(mismatches[:limit], "\n  "))
	}
}

func TestYJSymbolCatalog_ExtensionCoverage(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()
	pyLen := g.SymbolCount
	goLen := len(goSyms)

	if goLen < pyLen {
		t.Errorf("Go table has %d symbols, but golden defines %d — Go is missing %d symbols",
			goLen, pyLen, pyLen-goLen)
		return
	}

	// Go extends beyond the catalog with $N placeholders up to SID 1000.
	// Verify the extra symbols are simple $N placeholders.
	if goLen > pyLen {
		t.Logf("Go table extends %d symbols beyond catalog (SIDs %d–%d) with $N placeholders",
			goLen-pyLen, 10+pyLen, 10+goLen-1)
		for i := pyLen; i < goLen; i++ {
			sid := 10 + i
			expected := fmt.Sprintf("$%d", sid)
			if goSyms[i] != expected {
				t.Errorf("Extended Go symbol at index %d (SID %d) = %q, expected placeholder %q",
					i, sid, goSyms[i], expected)
			}
		}
	}
}

func TestYJSymbolCatalog_CurrentPreviewerTail(t *testing.T) {
	// Previewer 3.106 DigitalBook.nativeGetSymbolName exposes the current
	// shared-table tail through SID 859. PropertyNameUtil stops at 853, so
	// 854..859 are non-property shared symbols that must still be present in
	// the YJ shared symbol table.
	want := map[uint32]string{
		852: "page_regions",
		853: "bcSequenceNumber",
		854: "yj.conversion.flow_order",
		855: "yj.conversion.owner",
		856: "yj.conversion.layout",
		857: "yj.conversion.content_type",
		858: "yj.conversion.semantic_tag",
		859: "yj.conversion.group",
	}
	tbl := sharedTable()
	syms := tbl.Symbols()
	for sid, name := range want {
		idx := int(sid) - 10
		if idx < 0 || idx >= len(syms) {
			t.Fatalf("SID %d is outside shared table len=%d", sid, len(syms))
		}
		if got := syms[idx]; got != name {
			t.Errorf("sharedTable SID %d = %q, want %q", sid, got, name)
		}
		if got := resolveSharedSymbol(sid); got != name {
			t.Errorf("resolveSharedSymbol(%d) = %q, want %q", sid, got, name)
		}
		if !isSharedSymbolName(name) {
			t.Errorf("isSharedSymbolName(%q) = false", name)
		}
	}

	// SID 860 is book-local in the controlled Previewer fixture; it is not a
	// shared semantic name. Go deliberately extends the table with $N fallback
	// placeholders for unknown future/local numeric SIDs.
	if got := syms[860-10]; got != "$860" {
		t.Fatalf("sharedTable SID 860 = %q, want $860 fallback", got)
	}
}

func TestYJSymbolCatalog_NoDuplicates(t *testing.T) {
	tbl := sharedTable()
	goSyms := tbl.Symbols()

	seen := make(map[string]int, len(goSyms))
	for i, s := range goSyms {
		if s == "" {
			t.Errorf("Empty symbol at index %d (SID %d)", i, 10+i)
			continue
		}
		if prev, dup := seen[s]; dup {
			t.Errorf("Duplicate symbol %q at indices %d and %d (SID %d and %d)",
				s, prev, i, 10+prev, 10+i)
		}
		seen[s] = i
	}
}
