package kfx

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// Golden-file test: YJ symbol catalog parity with ION catalog.
//
// This test loads internal/kfx/testdata/yj_symbols_golden.json (generated by
// scripts/export_yj_symbol_catalog.py from the ION catalog) and verifies that
// Go's sharedTable() produces matching name, version, and per-SID symbol text.
//
// Regenerate golden:
//   python3 scripts/export_yj_symbol_catalog.py > internal/kfx/testdata/yj_symbols_golden.json
// ---------------------------------------------------------------------------

// yjSymbolsGolden maps the JSON structure produced by the export script.
type yjSymbolsGolden struct {
	Name        string   `json:"name"`
	Version     int      `json:"version"`
	SymbolCount int      `json:"symbol_count"`
	Symbols     []string `json:"symbols"`
}

func loadYjSymbolsGolden(t *testing.T) yjSymbolsGolden {
	t.Helper()
	raw, err := os.ReadFile("testdata/yj_symbols_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var g yjSymbolsGolden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	return g
}

func TestYJSymbolCatalog_NameAndVersion(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()

	if tbl.Name() != g.Name {
		t.Errorf("sharedTable name = %q, want %q", tbl.Name(), g.Name)
	}
	if tbl.Version() != g.Version {
		t.Errorf("sharedTable version = %d, want %d", tbl.Version(), g.Version)
	}
}

func TestYJSymbolCatalog_SymbolsMatchGolden(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()

	// Verify every golden symbol matches Go at the corresponding index.
	// Golden index i = SID 10+i.
	var mismatches []string
	for i, want := range g.Symbols {
		sid := 10 + i
		if i >= len(goSyms) {
			mismatches = append(mismatches, fmt.Sprintf("SID %d: Go table too short (len=%d, need ≥%d)", sid, len(goSyms), i+1))
			continue
		}
		got := goSyms[i]
		if got != want {
			mismatches = append(mismatches, fmt.Sprintf("SID %d: Go=%q Golden=%q", sid, got, want))
		}
	}

	if len(mismatches) > 0 {
		limit := len(mismatches)
		if limit > 20 {
			limit = 20
		}
		t.Errorf("Go vs golden symbol mismatches (%d total, showing first %d):\n  %s",
			len(mismatches), limit, strings.Join(mismatches[:limit], "\n  "))
	}
}

func TestYJSymbolCatalog_ExtensionCoverage(t *testing.T) {
	g := loadYjSymbolsGolden(t)
	tbl := sharedTable()
	goSyms := tbl.Symbols()
	pyLen := g.SymbolCount
	goLen := len(goSyms)

	if goLen < pyLen {
		t.Errorf("Go table has %d symbols, but golden defines %d — Go is missing %d symbols",
			goLen, pyLen, pyLen-goLen)
		return
	}

	// Go extends beyond the catalog with $N placeholders up to SID 1000.
	// Verify the extra symbols are simple $N placeholders.
	if goLen > pyLen {
		t.Logf("Go table extends %d symbols beyond catalog (SIDs %d–%d) with $N placeholders",
			goLen-pyLen, 10+pyLen, 10+goLen-1)
		for i := pyLen; i < goLen; i++ {
			sid := 10 + i
			expected := fmt.Sprintf("$%d", sid)
			if goSyms[i] != expected {
				t.Errorf("Extended Go symbol at index %d (SID %d) = %q, expected placeholder %q",
					i, sid, goSyms[i], expected)
			}
		}
	}
}

func TestYJSymbolCatalog_NoDuplicates(t *testing.T) {
	tbl := sharedTable()
	goSyms := tbl.Symbols()

	seen := make(map[string]int, len(goSyms))
	for i, s := range goSyms {
		if s == "" {
			t.Errorf("Empty symbol at index %d (SID %d)", i, 10+i)
			continue
		}
		if prev, dup := seen[s]; dup {
			t.Errorf("Duplicate symbol %q at indices %d and %d (SID %d and %d)",
				s, prev, i, 10+prev, 10+i)
		}
		seen[s] = i
	}
}
