package kfx

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"testing"
)

// ---------------------------------------------------------------------------
// Golden-file test: yj_versions KNOWN_FEATURES key parity with Calibre.
//
// This test loads internal/kfx/testdata/yj_versions_golden.json (generated by
// scripts/export_yj_versions.py from the Calibre Python source) and verifies
// that Go's KnownFeatures map has the same category→feature_key structure.
//
// Regenerate golden:
//   python3 scripts/export_yj_versions.py > internal/kfx/testdata/yj_versions_golden.json
// ---------------------------------------------------------------------------

// yjVersionsGolden maps the JSON structure from the export script.
type yjVersionsGolden struct {
	FeatureKeys     map[string][]string `json:"feature_keys"`
	FeatureKeysHash string              `json:"feature_keys_hash"`
}

func loadYjVersionsGolden(t *testing.T) yjVersionsGolden {
	t.Helper()
	raw, err := os.ReadFile("testdata/yj_versions_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var g yjVersionsGolden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	return g
}

func TestYJVersions_FeatureKeysMatch(t *testing.T) {
	g := loadYjVersionsGolden(t)

	// Build the same structure from Go's KnownFeatures
	goKeys := make(map[string][]string)
	for cat, keyMap := range KnownFeatures {
		var keys []string
		for k := range keyMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		goKeys[cat] = keys
	}

	// Compare categories
	pyCats := sortedKeys2(g.FeatureKeys)
	goCats := sortedKeys2(goKeys)

	// Check for missing/extra categories
	missingInGo := diff2(pyCats, goCats)
	extraInGo := diff2(goCats, pyCats)

	if len(missingInGo) > 0 {
		t.Errorf("Categories in Python golden but missing from Go KnownFeatures: %v", missingInGo)
	}
	if len(extraInGo) > 0 {
		t.Errorf("Categories in Go KnownFeatures but not in Python golden: %v", extraInGo)
	}

	// For each common category, compare feature keys
	for _, cat := range common2(pyCats, goCats) {
		pyFK := g.FeatureKeys[cat]
		goFK := goKeys[cat]

		missingKeys := diff2(pyFK, goFK)
		extraKeys := diff2(goFK, pyFK)

		if len(missingKeys) > 0 {
			t.Errorf("KnownFeatures[%q]: keys in Python but missing from Go: %v", cat, missingKeys)
		}
		if len(extraKeys) > 0 {
			t.Errorf("KnownFeatures[%q]: keys in Go but not in Python: %v", cat, extraKeys)
		}
	}
}

func TestYJVersions_FeatureKeysHash(t *testing.T) {
	g := loadYjVersionsGolden(t)

	// Recompute hash from Go's KnownFeatures and compare
	goKeys := make(map[string][]string)
	for cat, keyMap := range KnownFeatures {
		var keys []string
		for k := range keyMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		goKeys[cat] = keys
	}

	// Sort the entire map (same way the Python script does it)
	canonical, err := json.Marshal(goKeys)
	if err != nil {
		t.Fatalf("marshal Go keys: %v", err)
	}

	goHash := fmt.Sprintf("%x", sha256.Sum256(canonical))

	if goHash != g.FeatureKeysHash {
		// Show what categories/keys differ
		pyJSON, _ := json.Marshal(g.FeatureKeys)
		t.Errorf("Feature keys hash mismatch:\n  Python golden: %s\n  Go computed:   %s\n\nPython keys: %s\nGo keys:      %s",
			g.FeatureKeysHash, goHash, string(pyJSON), string(canonical))
	}
}

// helpers

func sortedKeys2(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// diff2 returns elements in a that are not in b.
func diff2(a, b []string) []string {
	bSet := make(map[string]bool, len(b))
	for _, s := range b {
		bSet[s] = true
	}
	var result []string
	for _, s := range a {
		if !bSet[s] {
			result = append(result, s)
		}
	}
	return result
}

// common2 returns sorted elements present in both a and b.
func common2(a, b []string) []string {
	bSet := make(map[string]bool, len(b))
	for _, s := range b {
		bSet[s] = true
	}
	var result []string
	for _, s := range a {
		if bSet[s] {
			result = append(result, s)
		}
	}
	sort.Strings(result)
	return result
}

