-- Tests for HelperClient module

require('busted.runner')()
local helper = require("spec/test_helper")

-- Fixture: one converted EPUB with its conversion-time position map, plus a
-- KRDS .yjf sidecar next to a fake KFX source.
local MAP = {
    version = 1,
    max_pid = 27200 + 16,
    fragments = {
        {
            path = "OEBPS/one.xhtml",
            elements = {
                ["div"] = { a = 1, s = 0, l = {} },
                ["div/p"] = { a = 2, s = 0, l = { 6, 10 } },
                ["div/p/em"] = { a = 2, s = 6, l = { 5 } },
                ["div/p[2]"] = { a = 1, s = 21, l = { 11 } },
                ["p"] = { a = 3, s = 0, l = { 16 } },
            },
            anchors = {
                { p = "div", eid = 1138, pid = 27100, t = 32,
                  nodes = { { p = "div/p[2]", n = 1, c = 21, v = 11 } } },
                { p = "div/p", eid = 1139, pid = 27115, t = 21,
                  nodes = {
                      { p = "div/p", n = 1, c = 0, v = 6 },
                      { p = "div/p/em", n = 1, c = 6, v = 5 },
                      { p = "div/p", n = 2, c = 11, v = 10 },
                  } },
                { p = "p", eid = 1140, pid = 27200, t = 16,
                  nodes = { { p = "p", n = 1, c = 0, v = 16 } } },
            },
        },
    },
}

-- Byte-exact KRDS fixture generated by python/krds_position.py: an
-- updated_lpr object (timestamp 1000) and an lpr object (timestamp 1100).
local SIDECAR_HEX = "00000000001ab1260200000000000000010100000002"
    .. "fe00000b757064617465645f6c70720300000e4153634541414141414141413a33"
    .. "0200000000000003e802ffffffffffffffff0300000003000000ff"
    .. "fe0000036c707207020300000e4153634541414141414141413a33"
    .. "02000000000000044cff"

local function sidecar_store()
    return (SIDECAR_HEX:gsub("%x%x", function(byte)
        return string.char(tonumber(byte, 16))
    end))
end

describe("HelperClient", function()
    local HelperClient
    local tmpdir
    local client_opts
    local epub_path
    local kfx_path
    local json = require("json")

    setup(function()
        helper.setup_complete()
    end)

    before_each(function()
        HelperClient = require("lua/helper_client")
        client_opts = { native_path_pattern = "%.kfx$" }

        tmpdir = os.tmpname()
        os.remove(tmpdir)
        require("libs/libkoreader-lfs").mkdir(tmpdir)
        epub_path = tmpdir .. "/book.epub"
        local map_file = io.open(tmpdir .. "/book.positions.json", "wb")
        map_file:write(json.encode(MAP))
        map_file:close()

        kfx_path = tmpdir .. "/book.kfx"
        local source = io.open(kfx_path, "wb")
        source:close()
        require("libs/libkoreader-lfs").mkdir(tmpdir .. "/book.sdr")
        local sidecar = io.open(tmpdir .. "/book.sdr/book.yjf", "wb")
        sidecar:write(sidecar_store())
        sidecar:close()
    end)

    after_each(function()
        os.remove(tmpdir .. "/book.positions.json")
        os.remove(tmpdir .. "/book.sdr/book.yjf")
        os.remove(kfx_path)
    end)

    describe("initialization", function()
        it("should accept helper_client in constructor", function()
            local mock_client = {}
            local client = HelperClient:new(mock_client)
            assert.equals(mock_client, client)
        end)
    end)

    describe("_run", function()
        it("should use runner function when available", function()
            local args_passed = nil
            local client = HelperClient:new({
                runner = function(args)
                    args_passed = args
                    return { ok = true }
                end,
            })
            local result = client:_run({ "test-binary", "test" })

            assert.is_not_nil(result)
            assert.equals("test", args_passed[2])
        end)

        it("should return error when binary not found", function()
            local client = HelperClient:new({ binary_path = "/nonexistent/binary" })
            local result, err = client:_run({ "/nonexistent/binary", "test" })

            assert.is_nil(result)
            assert.is_string(err)
        end)
    end)

    describe("native position sync", function()
        it("translates an XPointer through the in-process position map", function()
            local client = HelperClient:new(client_opts)
            local result, err = client:translatePosition(
                epub_path, "/body/DocFragment/body/div/p/em/text().4")

            assert.is_not_nil(result, err)
            assert.equals(1139, result.eid)
            assert.equals(27125, result.pid)
            assert.is_number(result.percent)
        end)

        it("reverse-translates a native long position", function()
            local client = HelperClient:new(client_opts)
            local forward = assert(client:translatePosition(
                epub_path, "/body/DocFragment/body/div/p/em/text().4"))
            local restored, err = client:translateNativePosition(epub_path, forward.long)

            assert.is_not_nil(restored, err)
            assert.equals(forward.long, restored.long)
            assert.equals("/body/DocFragment/body/div/p/em/text().4", restored.xpointer)
        end)

        it("reads the native sidecar position in-process", function()
            local client = HelperClient:new(client_opts)
            local result, err = client:readNativeProgress("B007N6JEII", kfx_path)

            assert.is_not_nil(result, err)
            assert.equals("AScEAAAAAAAA", result.long)
            assert.equals(3, result.pid)
            assert.equals(1100, result.timestamp_ms)
        end)

        it("writes and reads back exact sidecar progress", function()
            local client = HelperClient:new(client_opts)
            local position = {
                long = "ATwFAACbAAAA",
                pid = 442741,
                percent = 75.5,
            }

            local ok, err, percent, saved =
                client:saveNativeProgress("B007N6JEII", kfx_path, position)

            assert.is_true(ok, err)
            assert.is_nil(err)
            assert.equals(75.5, percent)
            assert.same({
                long = "ATwFAACbAAAA",
                pid = 442741,
                percent = 75.5,
            }, saved)

            local reread = assert(client:readNativeProgress("B007N6JEII", kfx_path))
            assert.equals("ATwFAACbAAAA", reread.long)
            assert.equals(442741, reread.pid)
        end)

        it("should expose a native progress runner seam", function()
            local client = HelperClient:new({
                native_progress_runner = function(asin, path, position)
                    return asin == "B007N6JEII" and path:match("%.kfx$")
                        and position.pid == 442741
                end,
            })
            assert.is_true(client:nativeProgressAvailable(
                "B007N6JEII", "/mnt/us/documents/book.kfx"
            ))
            assert.is_true(client:saveNativeProgress(
                "B007N6JEII", "/mnt/us/documents/book.kfx",
                { long = "ATwFAACbAAAA", pid = 442741 }
            ))
        end)

        it("should capability-gate exact sync for unsupported books", function()
            local client = HelperClient:new({ native_progress_available = true })
            assert.is_false(client:nativeProgressAvailable(
                "personal-document", "/mnt/us/documents/book.kfx"
            ))
            assert.is_false(client:nativeProgressAvailable(
                "B007N6JEII", "/tmp/book.kfx"
            ))
        end)

        it("should allow device capability to be overridden for compatibility tests", function()
            local client = HelperClient:new({ native_progress_available = false })
            assert.is_false(client:nativeProgressAvailable(
                "B007N6JEII", "/mnt/us/documents/book.kfx"
            ))
        end)

        it("should reject native progress paths outside the Kindle library", function()
            local invoked = false
            local client = HelperClient:new({
                native_progress_runner = function()
                    invoked = true
                    return true
                end,
            })
            local ok, err = client:saveNativeProgress(
                "B007N6JEII", "/tmp/book.kfx",
                { long = "ATwFAACbAAAA", pid = 442741 }
            )
            assert.is_false(ok)
            assert.equals("invalid native path", err)
            assert.is_false(invoked)
        end)

        it("reads both close-sync authorities in-process", function()
            local client = HelperClient:new(client_opts)

            local result, err = client:readCloseState(
                kfx_path,
                epub_path,
                "/body/DocFragment/body/div/p/em/text().4"
            )

            assert.is_not_nil(result, err)
            assert.is_truthy(result.ok)
            assert.equals(3, result.native.pid)
            assert.is_string(result.native_translate_error)
            assert.equals(27125, result.koreader.pid)
        end)
    end)

    describe("convert", function()
        it("should call _run with convert command", function()
            local client = HelperClient:new({
                runner = function(args)
                    return { ok = true, output_path = "/output.epub" }
                end,
            })
            client:setSettings({})

            local result = client:convert("/input.kfx", "/output.epub")

            assert.is_not_nil(result)
            assert.is_true(result.ok)
        end)
    end)
end)
